all:
	gcc -o in in.c list.c -lm
	gcc -o sum sum.c list.c -lm
	gcc -o merge merge.c list.c -lm
	gcc -o poly-sum poly-sum.c plist.c -lm
	gcc -o test-graph test-graph.c graph.c -lm
clean:
	rm in sum merge poly-sum test-graph
