all:
	gcc -o merge-sort.exe merge-sort.c utils.c -lm
	gcc -o merge-debug.exe merge-debug.c utils.c -lm
	gcc -o merge-inplace.exe merge-inplace.c utils.c -lm
	gcc -o merge-inv.exe merge-inv.c utils.c -lm
	gcc -o merge-sum.exe merge-sum.c utils.c -lm
	gcc -o merge-insert.exe merge-insert.c utils.c -lm
	gcc -o merge-maximal.exe merge-maximal.c utils.c -lm 
	gcc -o merge-tau.exe merge-tau.c utils.c -lm
	gcc -o closest_pair.exe closest_pair.c utils.c -lm
clean:
	rm merge-sort merge-debug merge-inplace merge-inv merge-sum merge-insert merge-maximal merge-tau closest_pair 
