all:
	gcc -o bad-commit bad-commit.c utils.c 
	gcc -o missing missing.c utils.c 
	gcc -o occurrences occurrences.c utils.c 
	gcc -o intersection intersection.c quick-sort.c utils.c 
	gcc -o word_search word_search.c utils.c 
	gcc -o perfect-square perfect-square.c utils.c 
clean:
	rm bad-commit missing occurrences intersection word_search perfect-square
