all:
	gcc -o bad-commit.exe bad-commit.c utils.c 
	gcc -o missing.exe missing.c utils.c 
	gcc -o occurrences.exe occurrences.c utils.c 
	gcc -o intersection.exe intersection.c quick-sort.c utils.c 
	gcc -o word_search.exe word_search.c utils.c 
	gcc -o perfect-square.exe perfect-square.c utils.c 
clean:
	rm bad-commit missing occurrences intersection word_search perfect-square
