all:
	gcc -o counting-sort-int.exe counting-sort-int.c utils.c 
	gcc -o counting-sort-char.exe counting-sort-char.c utils.c 
	gcc -o process-interval.exe process-interval.c utils.c 
	gcc -o radix-sort-int.exe radix-sort-int.c utils.c 
clean:
	rm counting-sort-int counting-sort-char process-interval radix-sort-int
