all:
	gcc -o back back.c list.c -lm
	gcc -o split split.c list.c -lm
	gcc -o crivo crivo.c list.c -lm
	gcc -o snake snake.c deque.c -lm
	gcc -o circular circular.c list.c -lm
	gcc -o replicate replicate.c list.c -lm
clean:
	rm back split crivo snake circular replicate
