all:
	gcc -o game.exe game.c utils.c
	gcc -o ruido.exe ruido.c utils.c 
	gcc -o stable.exe stable.c 
	gcc -o median.exe median.c utils.c
	gcc -o bubble.exe bubble.c utils.c
	gcc -o selection.exe selection.c utils.c
	gcc -o dictionary.exe dictionary.c utils.c
	gcc -o insertion.exe insertion.c utils.c
	gcc -o bubble-rec.exe bubble-rec.c utils.c
	gcc -o selection-rec.exe selection-rec.c utils.c
	gcc -o selection-dec.exe selection-dec.c utils.c
	gcc -o insertion-rec.exe insertion-rec.c utils.c
clean:
	rm game ruido stable median bubble selection dictionary insertion bubble-rec selection-rec selection-dec insertion-rec 
