all:
	gcc -o game game.c utils.c
	gcc -o ruido ruido.c utils.c 
	gcc -o stable stable.c 
	gcc -o median median.c utils.c
	gcc -o bubble bubble.c utils.c
	gcc -o selection selection.c utils.c
	gcc -o dictionary dictionary.c utils.c
	gcc -o insertion insertion.c utils.c
	gcc -o bubble-rec bubble-rec.c utils.c
	gcc -o selection-rec selection-rec.c utils.c
	gcc -o selection-dec selection-dec.c utils.c
	gcc -o insertion-rec insertion-rec.c utils.c
clean:
	rm game ruido stable median bubble selection dictionary insertion bubble-rec selection-rec selection-dec insertion-rec 
